branch-defaults:
  ABS-work:
    environment: flasky
  global:
    application_name: flasky
    branch: null
    default_ec2_keyname: ssh for flasky
    default_platform: Python 3.8
    default_region: ap-southeast-2
    include_git_submodules: true
    instance_profile: null
    platform name: null
    platform_version: null
    profile: eb-cli
    repository: null
    sc: git
    workspace_type: Application
  main:
    environment: flasky
    group-suffix: null
environment-defaults:
  flasky:
    branch: ABS-work
    repository: origin
global:
  application_name: flasky
  default_ec2_keyname: ssh for flasky
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
